Repository wecode-bootcamp-korea/27-2nd-ReadyBooks-frontend, pull requests merged in 2021-12, with the labels that each got.

#4 [27기 홍유진] nav bar 구현
  package-lock.json
  package.json
  public/images/images.md
  public/images/kakao_login_small.png
  src/components/Nav/Nav.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#1 [27기 김성현] login 페이지 -> js로 로그인 로그아웃 로직 구성
  .gitignore
  config.js
  package-lock.json
  public/images/kakaoLogin.png
  public/images/kakao_login_medium.png
  public/images/readyBooks.jpg
  public/index.html
  src/Router.js
  src/api/KakaoApi.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Login/Login.js
Labels: Status: Accepted

#6 [27기 김성현] login -> 백엔드 통신 endpoint 변경
  src/config.js
Labels: Status: 리뷰 요청

#7 [27기 김성현] Detail -> UI , 기능 완성
  public/data/detail.json
  public/images/littlePrince.jpeg
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Detail/DetailReviews/Review/Review.js
Labels: Status: 리뷰 요청

#5 [27기 김예슬] Footer 레이아웃
  src/Router.js
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#9 [27기 김성현] Detail -> 오타 수정 및 구매 버튼 부분 변경
  src/api/KakaoApi.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Detail/DetailReviews/Review/Review.js
Labels: Status: 리뷰 요청

#10 [27기 김예슬] Footer 수정
  src/Router.js
  src/components/Footer/Footer.js
Labels: Status: 수정 요청

#8 [27기 홍유진] 메인페이지 레이아웃 및 기능구현
  package-lock.json
  package.json
  public/data/bestBookdata 2.json
  public/data/bestBookdata.json
  public/data/bookdata.json
  public/data/data.md
  public/data/purchasedBookList.json
  public/index.html
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Main/BestSellerContainer 2/BestItems/BestItems 2.js
  src/pages/Main/BestSellerContainer/BestItem/BestItem.js
  src/pages/Main/BestSellerContainer/BestSellerContainer.js
  src/pages/Main/BooksContainer/BookItem/BookItem.js
  src/pages/Main/BooksContainer/BooksContainer.js
  src/pages/Main/BooksContainer/Pagination/Pagination.js
  src/pages/Main/Main.js
  src/pages/Main/MyBooks/MyBook/MyBook.js
  src/pages/Main/MyBooks/MyBooks.js
Labels: Status: 리뷰 요청

#11 [27기 김성현] 상세페이지 -> UI 완성
  public/data/book1.json
  public/data/book2.json
  public/data/detail.json
  public/data/reviews.json
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Detail/DetailReviews/Review/Review.js
  src/pages/Detail/DetailReviews/Reviews/Reviews.js
Labels: Status: 리뷰 요청

#12 [27기 김성현] detial 페이지 -> 백통신 부분
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Detail/DetailReviews/Reviews/Reviews.js
Labels: Status: 수정 요청

#15 [27기 김성현] 상세페이지 -> 멘토님 리뷰 반영
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Detail/DetailReviews/Reviews/Reviews.js
Labels: Status: 리뷰 요청

#13 [27기 홍유진] Image Mapping
  package-lock.json
  package.json
  public/data/bestBookdata 2.json
  public/data/bestBookdata.json
  public/data/bookdata.json
  public/data/purchasedBookList.json
  src/assets/엄지공주.jpeg
  src/config.js
  src/index.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Main/BestSellerContainer 2/BestItems/BestItems 2.js
  src/pages/Main/BestSellerContainer/BestItem/BestItem.js
  src/pages/Main/BestSellerContainer/BestSellerContainer.js
  src/pages/Main/BooksContainer/BookItem/BookItem.js
  src/pages/Main/BooksContainer/BooksContainer.js
  src/pages/Main/BooksContainer/Pagination/Pagination.js
  src/pages/Main/Main.js
  src/pages/Main/MyBooks/MyBook/MyBook.js
  src/pages/Main/MyBooks/MyBooks.js
Labels: Status: 리뷰 요청

#16 [27기 김성현] 상세페이지 -> pdf 보기, 미리보기 완료
  package-lock.json
  package.json
  src/components/Pdf/Pdf.js
  src/config.js
  src/index.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailContent/DetailContent.js
  src/pages/Detail/DetailReviews/DetailReviews.js
Labels: Status: 리뷰 요청

#17 [27기 김성현] 댓글 추가 후 댓글 다시 가져오기 수정
  public/data/book1.json
  public/data/book2.json
  public/data/detail.json
  public/data/reviews.json
  src/config.js
  src/pages/Detail/DetailReviews/DetailReviews.js
  src/pages/Detail/DetailReviews/Review/Review.js
Labels: Status: 리뷰 요청

#14 [27기 김예슬] 장바구니 통신 수정중
  src/pages/Cart/Cart.js
  src/pages/CartItem/CartItem.js
Labels: Status: 리뷰 요청

#18 [27기 김성현] pdf popup 할 때 scroll 없애기
  src/components/Pdf/Pdf.js
  src/index.js
Labels: Status: 리뷰 요청

#20 [27기 김예슬] 장바구니 기능 구현 완료
  src/pages/Cart/Cart.js
  src/pages/CartItem/CartItem.js
Labels: Status: 리뷰 요청

#19 [27기 김성현] Pdf 첫페이지, 마지막 페이지 알림창
  src/components/Pdf/Pdf.js
  src/config.js
Labels: Status: 리뷰 요청

#21 Add: mapping
  src/api/KakaoApi.js
  src/assets/엄지공주.jpeg
  src/config.js
  src/pages/Main/BestSellerContainer/BestItem/BestItem.js
  src/pages/Main/BestSellerContainer/BestSellerContainer.js
  src/pages/Main/BooksContainer/BookItem/BookItem.js
  src/pages/Main/BooksContainer/BooksContainer.js
  src/pages/Main/BooksContainer/Pagination/Pagination.js
  src/pages/Main/MyBooks/MyBook/MyBook.js
  src/pages/Main/MyBooks/MyBooks.js
Labels: Status: 리뷰 요청

#22 [27기 김성현] message 부분 문제 해결
  src/api/.KakaoApi.js.swp
  src/pages/Detail/DetailContent/DetailContent.js
Labels: Status: 리뷰 요청

#23 [27기 김예슬] 장바구니 min-height 수정
  src/pages/Cart/Cart.js
Labels: Status: 리뷰 요청

#24 [27기 김성현] minimal change
  src/api/.KakaoApi.js.swp
  src/api/KakaoApi.js
  src/components/Nav/Nav.js
  src/config.js
Labels: Status: 리뷰 요청

#25 [27기 김성현] Readme 수정
  README.md
  public/images/erd.png
Labels: Status: 리뷰 요청
